### PR TITLE
S3-Archiver Support

### PR DESCRIPTION
**Pull request by gshakir**

### CODE REVIEW

**Comment by avandecreme** [comment]
Thanks for the PR.
Please allow me some time to test it before merging.

**Comment by avandecreme** [comment]
Thanks. Merged!
I did some style fix.
I didn't test the s3 part because I don't have access to one.
I didn't test the hdfs part either because I don't have any instance running. Did you try it? I am not sure how well work the default `Configuration` constructor.
Also, right now `hadoop-common` is set as `provided` in the pom file so the user will have to add it to the path somehow.

**Comment by gshakir** [comment]
Thank you for merging and fixing the styles. I tested the S3 and HDFS archiver (using single pseudo cluster on my mac) . The default Configuration and Path constructor in HDFS uses your local core-site.xml and other configuration files from your Hadoop install to provide the right values.

**Comment by avandecreme** [comment]
> I tested the S3 and HDFS archiver (using single pseudo cluster on my mac) . The default Configuration and Path constructor in HDFS uses your local core-site.xml and other configuration files from your Hadoop install to provide the right values.

Great, I think I will be releasing a version 1.0 before the end of the month.

**Pull request merged**
